initial acs configuration for L1 and L2 Token User
pagopa/hub-spid-login-ms pull request #11
Opened 2021-05-04 13:16 UTC by AleDore

This PR enables Attribute authority endpoint to be called in the Assertion Consumer service controller

2021-05-10 11:33 UTC, BurnedMarshal requested changes

2021-05-10 11:33 UTC, BurnedMarshal commented on src/utils/jwt.ts
> +  fromEither(typeToExtract.decode(jwt.decode(jwtToken))).mapLeft(errorsToError);
Could throw `jwt.decode`?

2021-05-10 11:33 UTC, BurnedMarshal commented on src/utils/fetch.ts
> +// tslint:disable: no-any
disable rule only on single line

2021-05-10 11:33 UTC, BurnedMarshal commented on src/utils/config.ts
>    SERVER_PORT: fromNullableE(-1)(process.env.SERVER_PORT)
```
  SERVER_PORT: fromNullableE(DEFAULT_SERVER_PORT)(process.env.SERVER_PORT)
    .chain(_ => IntegerFromString.decode(_).mapLeft(() => DEFAULT_SERVER_PORT))
    .fold(identity, identity)
```
and maybe should be a `NonNegativeInteger`.

2021-05-10 11:33 UTC, BurnedMarshal commented on src/utils/config.ts
> +  DEFAULT_TOKEN_EXPIRATION: fromNullableE(-1)(
Why the default value should be set from env? We already have specific envs for L1 and L2 expirations

2021-05-10 11:37 UTC, BurnedMarshal requested changes

2021-05-10 11:37 UTC, BurnedMarshal commented on src/handlers/token.ts
> +          // tslint:disable-next-line: no-any
we need this?

2021-05-10 11:37 UTC, BurnedMarshal commented on src/handlers/token.ts
> +    .fold(identity, _ => res.status(200).json(_))
```suggestion
    .fold(() => res.status(500).json("Error while invalidating Token"), _ => res.status(200).json(_))
```

2021-05-10 14:14 UTC, AleDore commented on conf-testenv/users.json
> +      "familyName": "Rossi",
because the username is `mario.rossi` :D

2021-05-10 16:01 UTC, AleDore commented on src/handlers/token.ts
> +          // tslint:disable-next-line: no-any
Nope :)

2021-05-10 16:03 UTC, AleDore commented on src/types/request.ts
> +export const UpgradeTokenBody = t.exact(
Yep now we have it!

2021-05-11 10:44 UTC, BurnedMarshal requested changes

2021-05-11 10:44 UTC, BurnedMarshal commented on package.json
> +    "predeploy": "npm-run-all generate build dist:modules",
`generate` task is already in `prebuild`

2021-05-11 10:44 UTC, BurnedMarshal commented on src/app.ts
>        >(identity, ({ tokenStr, tokenUser }) =>
Can we add some logs on left path?

2021-05-11 10:44 UTC, BurnedMarshal commented on src/utils/config.ts
> +  })
Can we add `TOKEN_EXPIRATION` (now `DEFAULT_TOKEN_EXPIRATION`) in here?
`L1_TOKEN_EXPIRATION ` and `L2_TOKEN_EXPIRATION ` are required if `ENABLE_ADE_AA ` is `true`
`TOKEN_EXPIRATION` is required when `ENABLE_ADE_AA` is false.
Right?
```suggestion
  t.interface({
    ENABLE_ADE_AA: t.literal(false),
    TOKEN_EXPIRATION: NonNegativeInteger
  })
```

2021-05-11 10:44 UTC, BurnedMarshal commented on src/utils/config.ts
> +  L2_TOKEN_EXPIRATION: fromNullableE(-1)(process.env.L2_TOKEN_EXPIRATION)
Why the default value is `-1`? If we have an `AA` this parameter is required and `NonNegativeInteger`, can we use an undefined default value?
```
  L1_TOKEN_EXPIRATION: IntegerFromString.decode(process.env.L1_TOKEN_EXPIRATION)
    .mapLeft(_ => undefined)
    .fold(identity, identity),
  L2_TOKEN_EXPIRATION: IntegerFromString.decode(process.env.L2_TOKEN_EXPIRATION)
    .mapLeft(_ => undefined)
    .fold(identity, identity)
```

2021-05-11 10:44 UTC, BurnedMarshal commented on src/utils/config.ts
> +    .chain(_ => NonNegativeInteger.decode(_).mapLeft(() => -1))
Sorry for my mistake, the `NonNegativeInteger` type decoding already happen into `IConfig` in [here](https://github.com/pagopa/hub-spid-login-ms/pull/11/files#diff-285dea82a685fcd275e82141070c164a79a6650d46573cfd6303381afc47b28bR95)
We can remove this 
```suggestion
```

2021-05-12 07:29 UTC, BurnedMarshal submitted a review, later dismissed
LGTM apart 2 minor changes

2021-05-12 07:29 UTC, BurnedMarshal commented on src/app.ts
> +  logoutCallbackUrl: `${config.ACS_BASE_URL}/slo`,
Update `env.example` with the new ENV

2021-05-12 07:29 UTC, BurnedMarshal commented on src/utils/conversions.ts
> +    detail: errs instanceof Error ? errs.message : String(errorsToError(errs)),
```suggestion
    detail: errs instanceof Error ? errs.message : errorsToError(errs).message,
```

2021-05-12 08:36 UTC, merged