add pipelines
pagopa/hub-spid-login-ms pull request #4
Opened 2021-04-28 14:03 UTC by AleDore

This PR add azure devops pipelines

2021-04-30 07:34 UTC, pasqualedevita requested changes
@AleDore can I have a push permission on this repo? thanks

2021-04-30 12:41 UTC, AleDore commented on .devops/code-review-pipelines.yml
> +          displayName: 'Validate API specifications'
Nope i will remove it

2021-04-30 13:02 UTC, AleDore commented on .devops/code-review-pipelines.yml
> +          displayName: 'Unit tests exec'
done

2021-05-01 08:04 UTC, pasqualedevita commented
list of changes https://github.com/pagopa/hub-spid-login-ms/pull/4/commits/9e4fd9b18a64d74def40171a8b8ed577d3db785e:
1. add `.node-version` `.nvmrc ` and removed NODE_VERSION variable
2. removed duplicated variables section
3. change vmImage to ubuntu-latest (app service plan is on linux)
4. added more variables for multi environment (prod, uat)
5. added new variable $(DEFAULT_BRANCH) instead of master/main (we need to add it into azdevops)
6. refactor deploy stage with slot (deploy on staging slot, healthcheck, swap production and staging slot)

PS: app service does not has staging slot, maybe we have to add it or add an optional deploy stage without slot

2021-05-03 15:35 UTC, AleDore commented
/azp run

2021-05-03 17:42 UTC, pasqualedevita approved these changes
LGTM

2021-05-03 17:42 UTC, merged